# Generated by Django 2.1.1 on 2018-11-04 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='nomatch', message='number must be 6 digits', regex='^\\d{6}$')])),
                ('sequence', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='nomatch', message='sequence must be 4 digits', regex='^\\d{4}$')])),
                ('seqDescription', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.FilePathField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='nomatch', message='telephone ranges from 9 to 13 digits', regex='^\\d{9,13}$')])),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postal', models.CharField(max_length=15, null=True)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('contactType', models.CharField(choices=[('REG', 'REGULATORY'), ('TEC', 'TECHNICAL'), ('AGT', 'AGENT'), ('PRO', 'PROMOTIONAL')], max_length=3)),
                ('phone', models.CharField(max_length=15)),
                ('telephoneType', models.CharField(choices=[('BUS', 'Business Telephone Number'), ('FAX', 'Fax Telephone Number'), ('MOB', 'Mobile Telephone Number')], default='BUS', max_length=3)),
                ('email', models.EmailField(max_length=50)),
                ('contactName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('MGER', 'MANAGER'), ('BAS', 'BASIC')], default='BAS', max_length=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='applications.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('url', models.FilePathField()),
                ('dest_url', models.FilePathField(blank=True, max_length=200, null=True)),
                ('size', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='applications.File')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('root', 'root'), ('default', 'default'), ('folder', 'folder'), ('file', 'file'), ('tag', 'tag')], default='default', max_length=15)),
                ('sNumber', models.CharField(max_length=15)),
                ('parent', models.CharField(max_length=15)),
                ('original', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('destination', models.CharField(choices=[('CN', 'CN'), ('US', 'US')], default='CN', max_length=2)),
                ('description', models.CharField(max_length=255, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(max_length=60000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appinfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applications.Application')),
                ('dunso', models.CharField(max_length=15)),
                ('companyName', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('appType', models.CharField(max_length=50)),
                ('subId', models.CharField(max_length=15)),
                ('subType', models.CharField(max_length=50)),
                ('effType', models.CharField(blank=True, max_length=50, null=True)),
                ('subSubType', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applications.Node')),
                ('sNumber', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('eCode', models.CharField(max_length=50)),
                ('studyNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('stfType', models.CharField(blank=True, max_length=50, null=True)),
                ('species', models.CharField(blank=True, max_length=50, null=True)),
                ('root', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('control', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('substance', models.CharField(blank=True, max_length=50, null=True)),
                ('productName', models.CharField(blank=True, max_length=50, null=True)),
                ('dosage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='node',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='file',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='contact',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='applications.Application'),
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.Company'),
        ),
        migrations.AddField(
            model_name='application',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.Template'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('application', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('application', 'contactType')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('number', 'sequence')},
        ),
    ]
