# Generated by Django 2.1.1 on 2018-09-15 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('dunso', models.CharField(max_length=15)),
                ('companyName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('appType', models.CharField(max_length=50)),
                ('subId', models.CharField(max_length=15)),
                ('subType', models.CharField(max_length=50)),
                ('effType', models.CharField(max_length=50)),
                ('subSubType', models.CharField(max_length=50)),
                ('subNumber', models.CharField(max_length=15)),
                ('refNumber', models.CharField(max_length=15)),
                ('refType', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('description', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('sequence', models.CharField(max_length=50)),
                ('seqDescription', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('postal', models.CharField(max_length=15, null=True)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('contactType', models.CharField(choices=[('REG', 'REGULATORY'), ('TEC', 'TECHNICAL'), ('AGT', 'AGENT'), ('PRO', 'PROMOTIONAL')], max_length=3, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='applications.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('MGER', 'MANAGER'), ('BAS', 'BASIC')], default='BAS', max_length=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='applications.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=100)),
                ('size', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='applications.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('path', models.FilePathField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='applications.File')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('nid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(choices=[('ROOT', 'ROOT'), ('DEFAULT', 'DEFAULT'), ('FOLDER', 'FOLDER'), ('FILE', 'FILE'), ('TAG', 'TAG')], default='DEFAULT', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=15)),
                ('sNumber', models.CharField(max_length=15)),
                ('parent', models.CharField(max_length=15)),
                ('original', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='applications.Application')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('sNumber', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('eCode', models.CharField(max_length=50)),
                ('studyNumber', models.CharField(max_length=50)),
                ('stfType', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('root', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('control', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('substance', models.CharField(max_length=50)),
                ('productName', models.CharField(max_length=50)),
                ('dosage', models.CharField(max_length=50)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('destination', models.CharField(choices=[('CN', 'CN'), ('US', 'US')], default='CN', max_length=2)),
                ('description', models.CharField(max_length=255, null=True)),
                ('version', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(max_length=60000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.Company'),
        ),
        migrations.AddField(
            model_name='application',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.Template'),
        ),
        migrations.AddField(
            model_name='appinfo',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.Application'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('application', 'nid')},
        ),
    ]
