# Generated by Django 2.1.1 on 2018-09-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
