# Generated by Django 2.1 on 2018-09-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactType',
            field=models.CharField(choices=[('REG', 'REGULATORY'), ('TEC', 'TECHNICAL'), ('AGT', 'AGENT'), ('PRO', 'PROMOTIONAL')], max_length=3, unique=True),
        ),
    ]
