# Generated by Django 2.1 on 2018-09-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20180903_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
