# Generated by Django 2.1.1 on 2018-09-30 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20180915_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='appinfo',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applications.Application'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('ROOT', 'ROOT'), ('DEFAULT', 'DEFAULT'), ('FOLDER', 'FOLDER'), ('FILE', 'FILE'), ('TAG', 'TAG')], default='DEFAULT', max_length=15),
        ),
        migrations.AlterField(
            model_name='tag',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='applications.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('number', 'sequence')},
        ),
    ]
