# Generated by Django 2.1.1 on 2018-09-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20180929_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
