# Generated by Django 2.1.1 on 2018-09-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20180929_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('root', 'root'), ('default', 'default'), ('folder', 'folder'), ('file', 'file'), ('tag', 'tag')], default='DEFAULT', max_length=15),
        ),
    ]
