# Generated by Django 2.1.1 on 2018-10-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20181006_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telephoneType',
            field=models.CharField(choices=[('BUS', 'Business Telephone Number'), ('FAX', 'Fax Telephone Number'), ('MOB', 'Mobile Telephone Number')], default='BUS', max_length=3),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactType',
            field=models.CharField(choices=[('REG', 'REGULATORY'), ('TEC', 'TECHNICAL'), ('AGT', 'AGENT'), ('PRO', 'PROMOTIONAL')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('application', 'contactType')},
        ),
    ]
