# Generated by Django 2.1.1 on 2018-10-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20181006_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contactName',
            field=models.CharField(default='richyan', max_length=50),
            preserve_default=False,
        ),
    ]
