# Generated by Django 2.1.1 on 2018-10-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_contact_contactname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('application', 'id')},
        ),
    ]
