# Generated by Django 2.1.1 on 2018-10-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20181007_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('root', 'root'), ('default', 'default'), ('folder', 'folder'), ('file', 'file'), ('tag', 'tag')], default='default', max_length=15),
        ),
    ]
