# Generated by Django 2.1.1 on 2018-10-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_auto_20181008_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='seqDescription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
